import type { Moment } from '../types/liveTypes';

export const MOMENTS: Moment[] = [
  {
    id: 'saturday_lunch',
    emoji: '🌞',
    label: 'Saturday lunch',
    description: 'Relaxed, sunny, something refreshing',
    tags: ['light', 'carbonated', 'citrus'],
    timeOfDay: 'afternoon',
    season: 'summer',
    social: 'social',
  },
  {
    id: 'sunday_dinner',
    emoji: '🍷',
    label: 'Sunday dinner',
    description: 'Needs to pair with food',
    tags: ['complex', 'dry'],
    timeOfDay: 'evening',
    season: 'anytime',
    social: 'anytime',
  },
  {
    id: 'friday_night',
    emoji: '🎉',
    label: 'Friday night out',
    description: 'Celebratory, something to sip',
    tags: ['bold', 'carbonated'],
    timeOfDay: 'evening',
    season: 'anytime',
    social: 'social',
  },
  {
    id: 'after_work',
    emoji: '😮‍💨',
    label: 'After work',
    description: 'Unwinding, decompressing',
    tags: ['bold', 'complex'],
    timeOfDay: 'evening',
    season: 'anytime',
    social: 'solo',
  },
  {
    id: 'summer_bbq',
    emoji: '☀️',
    label: 'Summer BBQ',
    description: 'Sessionable, easy, crowd-pleasing',
    tags: ['light', 'carbonated'],
    timeOfDay: 'afternoon',
    season: 'summer',
    social: 'social',
  },
  {
    id: 'dry_january',
    emoji: '🌿',
    label: 'Dry January',
    description: 'Making it feel special',
    tags: ['complex', 'bitter'],
    timeOfDay: 'anytime',
    season: 'winter',
    social: 'anytime',
  },
  {
    id: 'post_workout',
    emoji: '🏃',
    label: 'Post-workout',
    description: 'Clean, functional, refreshing',
    tags: ['light', 'clean'],
    timeOfDay: 'morning',
    season: 'anytime',
    social: 'solo',
  },
  {
    id: 'holiday_gathering',
    emoji: '🎄',
    label: 'Holiday gathering',
    description: 'Festive, impressive, celebratory',
    tags: ['bold', 'carbonated', 'complex'],
    timeOfDay: 'evening',
    season: 'winter',
    social: 'social',
  },
  {
    id: 'casual_night',
    emoji: '🍕',
    label: 'Casual night in',
    description: 'No fuss, just something easy',
    tags: ['light', 'dry'],
    timeOfDay: 'evening',
    season: 'anytime',
    social: 'solo',
  },
  {
    id: 'work_lunch',
    emoji: '💼',
    label: 'Work lunch',
    description: 'Professional, light, sharp',
    tags: ['dry', 'light'],
    timeOfDay: 'afternoon',
    season: 'anytime',
    social: 'social',
  },
];
